print('What do you get when you cross a snowman and a vampire?')
input ()
print('Frostbite')
print()
print('I just stepped on a cornflake...')
input ()
print('I guess you could call me a cereal killer!')
print()
print('I was in a punk band in the 80s called "Missing Cat"...')
input()
print('You might remember our flyers!')
